apiVersion: v1
data:
  kubeconfig: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJek1EZ3lOekEzTVRneU5Gb1hEVE16TURneU5UQTNNVGd5TkZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTURZCkRtN1lKU0tyZloyQWdYTlpZczZ1SlhtSTBqNWFTZncxa3BHWGZxUzJEVjhJenFKbjB2ZEZRNjJwbnMvSEV6eHYKSXIydU1vRllDcERvOXUxT3I3TDQvVGo2WXRBSnoyelhwcFJQRHpXR0ZyWUpBaDI0SktHT3ZGb0dSSkoyWDdNMgpINDdhdHlDbVYxSlJsVzgxd3pUcnhpRVJaSkNlcE93cjNGL2hKYyt0YXRRMi9oQ3Nzb2tleEsrUGVlU3F1RVVECllvblhNbDFuVWRqNGllV1JWL2lNTHZySlR0UUI1eXovL0FVdHcrTm9NSzJ5WmhmenNjSUFHY3ptcTFZVnQ4aEYKR0NMWDVYcExnWi82eDVybkRCdDMyUmFrZXFpWWRPbTJ2cXlwaEI1dUxKY0xrYkd1aHoyRjNqTFdxT3pqdDRLKwpqNWxic3lvYlZmRzJHOWxJTWpFQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJTa2lkWFZEK1hxUnBFUjRBUW9sQnlPQnI1UjRUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFXWDBrZjlRNApzRThiR0dFZG5qRm1BNGNsd0xJdnh6KzNUcEIvRmdZT04yWXBsZSt3TGc3RHg0WjdMZE8wYVFsMDk3SXh6Qk9hClJremk4ejloUDBZSWtnWVlMcTRrcmF4aXFmYWMwVCtNd3NIUWFjbk1UMXNnV3EyS2NXUTdMQ0xUd0YxbG5nelcKdlVXclovZmNKTnlJUk4wUWY3TEw4RGt1SVFQeFhpZk9hU3RRbkRFVHRycFFJelRmWCttUldYTk9tQmVkNFU3TgpMZ0hoZENRMWdEbWNRVUZMdkNzOFdyNXhUUnNuZ3JOV3ZwR3U4Nm5HNkxOZVV0ZHhrVmppYm9pYTJKRkkrTmppCkJWeWF2b2lLT0Y1RURqaTVDVmtFcWtLSmIvRjMrTTJ2MUlFRldXaHBuM3laYU9TSWEvSDBMMnVqcHc2Tmw2MVMKbHdua2ZPVmtnblpHY0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
        server: https://control-plane.minikube.internal:8443
      name: ""
    contexts: null
    current-context: ""
    kind: Config
    preferences: {}
    users: null
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-01T13:06:14Z"
  name: cluster-info
  namespace: kube-public
