apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{},"name":"urlcontroller-manager-role"},"rules":[{"apiGroups":["demo.demo.kcd.io"],"resources":["demoresources"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["demo.demo.kcd.io"],"resources":["demoresources/finalizers"],"verbs":["update"]},{"apiGroups":["demo.demo.kcd.io"],"resources":["demoresources/status"],"verbs":["get","patch","update"]}]}
  creationTimestamp: "2023-10-11T06:22:25Z"
  name: urlcontroller-manager-role
rules:
- apiGroups:
  - demo.demo.kcd.io
  resources:
  - demoresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - demo.demo.kcd.io
  resources:
  - demoresources/finalizers
  verbs:
  - update
- apiGroups:
  - demo.demo.kcd.io
  resources:
  - demoresources/status
  verbs:
  - get
  - patch
  - update
