apiVersion: storage.k8s.io/v1
kind: CSINode
metadata:
  annotations:
    storage.alpha.kubernetes.io/migrated-plugins: kubernetes.io/aws-ebs,kubernetes.io/azure-disk,kubernetes.io/azure-file,kubernetes.io/cinder,kubernetes.io/gce-pd,kubernetes.io/vsphere-volume
  creationTimestamp: "2023-09-01T13:06:11Z"
  name: minikube
  ownerReferences:
  - apiVersion: v1
    kind: Node
    name: minikube
    uid: 7430868f-dbf0-4399-916e-ec5f730ad7fc
spec:
  drivers: null
