apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"go-app","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"go-app"}},"template":{"metadata":{"labels":{"app":"go-app"}},"spec":{"containers":[{"image":"sharmag07/url-short:a2","name":"go-app","ports":[{"containerPort":9090}],"resources":{"limits":{"cpu":"800m","memory":"128Mi"}}}]}}}}
  creationTimestamp: "2023-10-31T07:09:41Z"
  name: go-app
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: go-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
    spec:
      containers:
      - image: sharmag07/url-short:a2
        imagePullPolicy: IfNotPresent
        name: go-app
        ports:
        - containerPort: 9090
          protocol: TCP
        resources:
          limits:
            cpu: 800m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
