apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2023-09-01T13:06:13Z"
  labels:
    endpointslice.kubernetes.io/skip-mirror: "true"
  name: kubernetes
  namespace: default
subsets:
- addresses:
  - ip: 192.168.49.2
  ports:
  - name: https
    port: 8443
    protocol: TCP
