apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2023-11-02T06:50:24Z"
involvedObject:
  apiVersion: apps/v1
  kind: ReplicaSet
  name: go-app-697df4b455
  namespace: default
  resourceVersion: "761063"
  uid: 3c3860ef-983e-4f62-a807-7fa6ee67c3ab
kind: Event
lastTimestamp: "2023-11-02T06:50:24Z"
message: 'Created pod: go-app-697df4b455-j7lrl'
metadata:
  creationTimestamp: "2023-11-02T06:50:24Z"
  name: go-app-697df4b455.1793bbaa5eb21735
  namespace: default
reason: SuccessfulCreate
reportingComponent: ""
reportingInstance: ""
source:
  component: replicaset-controller
type: Normal
