apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    meta.helm.sh/release-name: katafygio
    meta.helm.sh/release-namespace: default
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
    volume.kubernetes.io/storage-provisioner: k8s.io/minikube-hostpath
  creationTimestamp: "2023-10-26T08:14:20Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: katafygio
    app.kubernetes.io/managed-by: Helm
    chart: katafygio-0.5.1
    heritage: Helm
    release: katafygio
  name: katafygio
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  volumeMode: Filesystem
  volumeName: pvc-ddf27608-1408-4917-9c9d-7e9d9c9d967c
