apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: "1"
    deployment.kubernetes.io/max-replicas: "2"
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2023-10-31T08:40:53Z"
  labels:
    app: go-app
    pod-template-hash: 5d98fdf646
  name: go-app-5d98fdf646
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: Deployment
    name: go-app
    uid: e4f66a27-c56d-431d-a506-d920c0587721
spec:
  replicas: 0
  selector:
    matchLabels:
      app: go-app
      pod-template-hash: 5d98fdf646
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        pod-template-hash: 5d98fdf646
    spec:
      containers:
      - image: sharmag07/url-short:a2
        imagePullPolicy: IfNotPresent
        name: go-app
        ports:
        - containerPort: 9090
          protocol: TCP
        resources:
          limits:
            cpu: 800m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
