apiVersion: demo.demo.kcd.io/v1
kind: UrlResource1
metadata:
  labels:
    app.kubernetes.io/name: urlresource1
    app.kubernetes.io/instance: urlresource1-sample
    app.kubernetes.io/part-of: project1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: project1
  name: urlresource1-sample
spec:
  targetURLs:
    - "https://www.hosting.co.uk/pro-services/?/post/2021/12/08/$5982-!"
    - "https://www.flipkart.com/mobile-phones-store"
    - "https://www.amazon.in/mobile-phones/b?ie=UTF8&node=1389401031"