addressType: IPv4
apiVersion: discovery.k8s.io/v1
endpoints:
- addresses:
  - 10.244.0.83
  conditions:
    ready: true
    serving: true
    terminating: false
  nodeName: minikube
  targetRef:
    kind: Pod
    name: project-controller-manager-649894599c-kz855
    namespace: project-system
    uid: c7434802-c595-4701-add6-57cd5e14fdfb
kind: EndpointSlice
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-11-02T08:53:16Z"
  creationTimestamp: "2023-10-11T16:15:22Z"
  generateName: project-controller-manager-metrics-service-
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: project
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: project
    control-plane: controller-manager
    endpointslice.kubernetes.io/managed-by: endpointslice-controller.k8s.io
    kubernetes.io/service-name: project-controller-manager-metrics-service
  name: project-controller-manager-metrics-service-xdpt9
  namespace: project-system
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Service
    name: project-controller-manager-metrics-service
    uid: da25976b-9cd2-4bff-adfd-4866f780eb59
ports:
- name: https
  port: 8443
  protocol: TCP
