apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-11-02T06:41:48Z"
  creationTimestamp: "2023-10-11T16:15:22Z"
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: project
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: project
    control-plane: controller-manager
  name: project-controller-manager-metrics-service
  namespace: project-system
subsets:
- notReadyAddresses:
  - ip: 10.244.0.83
    nodeName: minikube
    targetRef:
      kind: Pod
      name: project-controller-manager-649894599c-kz855
      namespace: project-system
      uid: c7434802-c595-4701-add6-57cd5e14fdfb
  ports:
  - name: https
    port: 8443
    protocol: TCP
