apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2023-11-02T06:17:29Z"
deprecatedLastTimestamp: "2023-11-02T06:17:29Z"
deprecatedSource:
  component: project-controller-manager-649894599c-kz855_19021f11-f309-4b4c-93b2-0705aadda701
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-11-02T06:17:29Z"
  name: f4bd82be.demo.kcd.io.1793b9de840abde2
  namespace: project-system
note: project-controller-manager-649894599c-kz855_19021f11-f309-4b4c-93b2-0705aadda701
  became leader
reason: LeaderElection
regarding:
  apiVersion: coordination.k8s.io/v1
  kind: Lease
  name: f4bd82be.demo.kcd.io
  namespace: project-system
  resourceVersion: "758779"
  uid: 973b25ad-2cd6-466e-b070-2a5c5914f8ec
reportingController: project-controller-manager-649894599c-kz855_19021f11-f309-4b4c-93b2-0705aadda701
type: Normal
