apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2023-11-02T09:00:53Z"
involvedObject:
  apiVersion: coordination.k8s.io/v1
  kind: Lease
  name: f4bd82be.demo.kcd.io
  namespace: project-system
  resourceVersion: "769996"
  uid: 973b25ad-2cd6-466e-b070-2a5c5914f8ec
kind: Event
lastTimestamp: "2023-11-02T09:00:53Z"
message: project-controller-manager-649894599c-kz855_b3771ce5-4df8-48a9-9503-2bbd50b6d23c
  became leader
metadata:
  creationTimestamp: "2023-11-02T09:00:53Z"
  name: f4bd82be.demo.kcd.io.1793c2c925c855d9
  namespace: project-system
reason: LeaderElection
reportingComponent: project-controller-manager-649894599c-kz855_b3771ce5-4df8-48a9-9503-2bbd50b6d23c
reportingInstance: ""
source:
  component: project-controller-manager-649894599c-kz855_b3771ce5-4df8-48a9-9503-2bbd50b6d23c
type: Normal
