apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2023-11-02T07:16:43Z"
involvedObject:
  apiVersion: coordination.k8s.io/v1
  kind: Lease
  name: f4bd82be.demo.kcd.io
  namespace: project-system
  resourceVersion: "762863"
  uid: 973b25ad-2cd6-466e-b070-2a5c5914f8ec
kind: Event
lastTimestamp: "2023-11-02T07:16:43Z"
message: project-controller-manager-649894599c-kz855_5cd09346-d6a1-4dfa-b97d-d02cd0a38ba7
  became leader
metadata:
  creationTimestamp: "2023-11-02T07:16:43Z"
  name: f4bd82be.demo.kcd.io.1793bd19d399f223
  namespace: project-system
reason: LeaderElection
reportingComponent: project-controller-manager-649894599c-kz855_5cd09346-d6a1-4dfa-b97d-d02cd0a38ba7
reportingInstance: ""
source:
  component: project-controller-manager-649894599c-kz855_5cd09346-d6a1-4dfa-b97d-d02cd0a38ba7
type: Normal
