apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2023-11-02T07:09:18Z"
involvedObject:
  apiVersion: coordination.k8s.io/v1
  kind: Lease
  name: f4bd82be.demo.kcd.io
  namespace: project-system
  resourceVersion: "762359"
  uid: 973b25ad-2cd6-466e-b070-2a5c5914f8ec
kind: Event
lastTimestamp: "2023-11-02T07:09:18Z"
message: project-controller-manager-649894599c-kz855_c05228f5-93fc-4034-b9c9-570b85e912f7
  became leader
metadata:
  creationTimestamp: "2023-11-02T07:09:18Z"
  name: f4bd82be.demo.kcd.io.1793bcb2616cf0b8
  namespace: project-system
reason: LeaderElection
reportingComponent: project-controller-manager-649894599c-kz855_c05228f5-93fc-4034-b9c9-570b85e912f7
reportingInstance: ""
source:
  component: project-controller-manager-649894599c-kz855_c05228f5-93fc-4034-b9c9-570b85e912f7
type: Normal
