apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2023-11-02T06:02:45Z"
deprecatedLastTimestamp: "2023-11-02T06:02:45Z"
deprecatedSource:
  component: project-controller-manager-649894599c-kz855_1cc733c9-662c-4ea4-8f1d-ac69cc113a3f
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-11-02T06:02:45Z"
  name: f4bd82be.demo.kcd.io.1793b910ac14fe46
  namespace: project-system
note: project-controller-manager-649894599c-kz855_1cc733c9-662c-4ea4-8f1d-ac69cc113a3f
  became leader
reason: LeaderElection
regarding:
  apiVersion: coordination.k8s.io/v1
  kind: Lease
  name: f4bd82be.demo.kcd.io
  namespace: project-system
  resourceVersion: "757775"
  uid: 973b25ad-2cd6-466e-b070-2a5c5914f8ec
reportingController: project-controller-manager-649894599c-kz855_1cc733c9-662c-4ea4-8f1d-ac69cc113a3f
type: Normal
