apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2023-11-02T07:16:43Z"
deprecatedLastTimestamp: "2023-11-02T07:16:43Z"
deprecatedSource:
  component: project-controller-manager-649894599c-kz855_5cd09346-d6a1-4dfa-b97d-d02cd0a38ba7
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-11-02T07:16:43Z"
  name: f4bd82be.demo.kcd.io.1793bd19d399f223
  namespace: project-system
note: project-controller-manager-649894599c-kz855_5cd09346-d6a1-4dfa-b97d-d02cd0a38ba7
  became leader
reason: LeaderElection
regarding:
  apiVersion: coordination.k8s.io/v1
  kind: Lease
  name: f4bd82be.demo.kcd.io
  namespace: project-system
  resourceVersion: "762863"
  uid: 973b25ad-2cd6-466e-b070-2a5c5914f8ec
reportingController: project-controller-manager-649894599c-kz855_5cd09346-d6a1-4dfa-b97d-d02cd0a38ba7
type: Normal
