apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2023-11-02T08:23:23Z"
deprecatedLastTimestamp: "2023-11-02T08:23:23Z"
deprecatedSource:
  component: project-controller-manager-649894599c-kz855_9ee2641f-58b6-4cb1-b113-f433d74b30fe
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-11-02T08:23:23Z"
  name: f4bd82be.demo.kcd.io.1793c0bd24eb02e9
  namespace: project-system
note: project-controller-manager-649894599c-kz855_9ee2641f-58b6-4cb1-b113-f433d74b30fe
  became leader
reason: LeaderElection
regarding:
  apiVersion: coordination.k8s.io/v1
  kind: Lease
  name: f4bd82be.demo.kcd.io
  namespace: project-system
  resourceVersion: "767431"
  uid: 973b25ad-2cd6-466e-b070-2a5c5914f8ec
reportingController: project-controller-manager-649894599c-kz855_9ee2641f-58b6-4cb1-b113-f433d74b30fe
type: Normal
