apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2023-11-02T05:25:50Z"
deprecatedLastTimestamp: "2023-11-02T05:25:50Z"
deprecatedSource:
  component: project-controller-manager-649894599c-kz855_ce92e626-40a9-4975-9513-eacf8e51ce69
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-11-02T05:25:50Z"
  name: f4bd82be.demo.kcd.io.1793b70cff274a0c
  namespace: project-system
note: project-controller-manager-649894599c-kz855_ce92e626-40a9-4975-9513-eacf8e51ce69
  became leader
reason: LeaderElection
regarding:
  apiVersion: coordination.k8s.io/v1
  kind: Lease
  name: f4bd82be.demo.kcd.io
  namespace: project-system
  resourceVersion: "755267"
  uid: 973b25ad-2cd6-466e-b070-2a5c5914f8ec
reportingController: project-controller-manager-649894599c-kz855_ce92e626-40a9-4975-9513-eacf8e51ce69
type: Normal
