apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2023-11-02T07:31:27Z"
involvedObject:
  apiVersion: coordination.k8s.io/v1
  kind: Lease
  name: f4bd82be.demo.kcd.io
  namespace: project-system
  resourceVersion: "763876"
  uid: 973b25ad-2cd6-466e-b070-2a5c5914f8ec
kind: Event
lastTimestamp: "2023-11-02T07:31:27Z"
message: project-controller-manager-649894599c-kz855_12713481-45a8-4e67-89b3-46b97c2e32c1
  became leader
metadata:
  creationTimestamp: "2023-11-02T07:31:27Z"
  name: f4bd82be.demo.kcd.io.1793bde7d44ebe0f
  namespace: project-system
reason: LeaderElection
reportingComponent: project-controller-manager-649894599c-kz855_12713481-45a8-4e67-89b3-46b97c2e32c1
reportingInstance: ""
source:
  component: project-controller-manager-649894599c-kz855_12713481-45a8-4e67-89b3-46b97c2e32c1
type: Normal
