apiVersion: coordination.k8s.io/v1
kind: Lease
metadata:
  creationTimestamp: "2023-10-16T19:01:42Z"
  name: f4bd82be.demo.kcd.io
  namespace: project-system
spec:
  acquireTime: "2023-11-02T07:38:58.976901Z"
  holderIdentity: project-controller-manager-649894599c-kz855_d8a5c07a-71fa-4c30-9dd1-f4d046b7ea18
  leaseDurationSeconds: 15
  leaseTransitions: 387
  renewTime: "2023-11-02T07:39:25.231561Z"
