apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"rbac","app.kubernetes.io/created-by":"project","app.kubernetes.io/instance":"leader-election-rolebinding","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"rolebinding","app.kubernetes.io/part-of":"project"},"name":"project-leader-election-rolebinding","namespace":"project-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"project-leader-election-role"},"subjects":[{"kind":"ServiceAccount","name":"project-controller-manager","namespace":"project-system"}]}
  creationTimestamp: "2023-10-11T16:15:22Z"
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: project
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: project
  name: project-leader-election-rolebinding
  namespace: project-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: project-leader-election-role
subjects:
- kind: ServiceAccount
  name: project-controller-manager
  namespace: project-system
