apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-11-02T06:32:58Z"
  creationTimestamp: "2023-10-11T06:22:25Z"
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: urlcontroller
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: service
    app.kubernetes.io/part-of: urlcontroller
    control-plane: controller-manager
  name: urlcontroller-controller-manager-metrics-service
  namespace: urlcontroller-system
subsets:
- notReadyAddresses:
  - ip: 10.244.0.81
    nodeName: minikube
    targetRef:
      kind: Pod
      name: urlcontroller-controller-manager-6584756fdd-w4ws2
      namespace: urlcontroller-system
      uid: 07529bad-3160-4fa8-a8ae-9885334dd131
  ports:
  - name: https
    port: 8443
    protocol: TCP
