apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2023-11-02T06:01:07Z"
involvedObject:
  apiVersion: coordination.k8s.io/v1
  kind: Lease
  name: 69dab0fe.urlshortner.juniper
  namespace: urlcontroller-system
  resourceVersion: "757640"
  uid: df537228-fad1-4aa0-b7b1-16a00f26f8d1
kind: Event
lastTimestamp: "2023-11-02T06:01:07Z"
message: urlcontroller-controller-manager-6584756fdd-w4ws2_5f063125-7c49-440d-8d36-c0ed382b7c80
  became leader
metadata:
  creationTimestamp: "2023-11-02T06:01:07Z"
  name: 69dab0fe.urlshortner.juniper.1793b8f9e78f81a0
  namespace: urlcontroller-system
reason: LeaderElection
reportingComponent: urlcontroller-controller-manager-6584756fdd-w4ws2_5f063125-7c49-440d-8d36-c0ed382b7c80
reportingInstance: ""
source:
  component: urlcontroller-controller-manager-6584756fdd-w4ws2_5f063125-7c49-440d-8d36-c0ed382b7c80
type: Normal
