apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2023-11-02T08:52:15Z"
involvedObject:
  apiVersion: coordination.k8s.io/v1
  kind: Lease
  name: 69dab0fe.urlshortner.juniper
  namespace: urlcontroller-system
  resourceVersion: "769389"
  uid: df537228-fad1-4aa0-b7b1-16a00f26f8d1
kind: Event
lastTimestamp: "2023-11-02T08:52:15Z"
message: urlcontroller-controller-manager-6584756fdd-w4ws2_e86c63b4-4f4f-49ab-a089-31995bc3d18b
  became leader
metadata:
  creationTimestamp: "2023-11-02T08:52:15Z"
  name: 69dab0fe.urlshortner.juniper.1793c2506fb78ea3
  namespace: urlcontroller-system
reason: LeaderElection
reportingComponent: urlcontroller-controller-manager-6584756fdd-w4ws2_e86c63b4-4f4f-49ab-a089-31995bc3d18b
reportingInstance: ""
source:
  component: urlcontroller-controller-manager-6584756fdd-w4ws2_e86c63b4-4f4f-49ab-a089-31995bc3d18b
type: Normal
