apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2023-11-02T06:53:19Z"
involvedObject:
  apiVersion: coordination.k8s.io/v1
  kind: Lease
  name: 69dab0fe.urlshortner.juniper
  namespace: urlcontroller-system
  resourceVersion: "761244"
  uid: df537228-fad1-4aa0-b7b1-16a00f26f8d1
kind: Event
lastTimestamp: "2023-11-02T06:53:19Z"
message: urlcontroller-controller-manager-6584756fdd-w4ws2_1133e319-53e2-418d-923b-93069cc8821e
  became leader
metadata:
  creationTimestamp: "2023-11-02T06:53:19Z"
  name: 69dab0fe.urlshortner.juniper.1793bbd2fbaa5f9a
  namespace: urlcontroller-system
reason: LeaderElection
reportingComponent: urlcontroller-controller-manager-6584756fdd-w4ws2_1133e319-53e2-418d-923b-93069cc8821e
reportingInstance: ""
source:
  component: urlcontroller-controller-manager-6584756fdd-w4ws2_1133e319-53e2-418d-923b-93069cc8821e
type: Normal
