apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"rbac","app.kubernetes.io/created-by":"urlcontroller","app.kubernetes.io/instance":"leader-election-rolebinding","app.kubernetes.io/managed-by":"kustomize","app.kubernetes.io/name":"rolebinding","app.kubernetes.io/part-of":"urlcontroller"},"name":"urlcontroller-leader-election-rolebinding","namespace":"urlcontroller-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"urlcontroller-leader-election-role"},"subjects":[{"kind":"ServiceAccount","name":"urlcontroller-controller-manager","namespace":"urlcontroller-system"}]}
  creationTimestamp: "2023-10-11T06:22:25Z"
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: urlcontroller
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: urlcontroller
  name: urlcontroller-leader-election-rolebinding
  namespace: urlcontroller-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: urlcontroller-leader-election-role
subjects:
- kind: ServiceAccount
  name: urlcontroller-controller-manager
  namespace: urlcontroller-system
